<?php
namespace App\Http\Controllers;
use App\Models\{Commission,Customer,InventoryItem,Invoice,Payment,ServiceJob,User}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class OperationsController extends Controller {
 public function dashboard(){ $today=now()->startOfDay(); return view('dashboard',['jobsToday'=>ServiceJob::whereBetween('scheduled_at',[$today,now()->endOfDay()])->count(),'activeJobs'=>ServiceJob::whereIn('status',['Dispatched','In Progress'])->count(),'lowStock'=>InventoryItem::whereColumn('stock','<=','reorder_level')->count(),'revenue'=>Invoice::where('status','Paid')->sum('total'),'upcoming'=>ServiceJob::with(['customer','technician'])->where('scheduled_at','>=',now())->orderBy('scheduled_at')->take(6)->get(),'alerts'=>InventoryItem::whereColumn('stock','<=','reorder_level')->orderBy('stock')->take(5)->get()]); }
 public function customers(){return view('customers.index',['customers'=>Customer::latest()->paginate(10)]);}
 public function storeCustomer(Request $r){Customer::create($r->validate(['name'=>'required|max:255','phone'=>'required|max:50','email'=>'nullable|email','address'=>'required','type'=>'required']));return back()->with('success','Customer saved.');}
 public function jobs(){return view('jobs.index',['jobs'=>ServiceJob::with(['customer','technician'])->latest('scheduled_at')->paginate(12),'customers'=>Customer::orderBy('name')->get(),'technicians'=>User::where('role','technician')->orderBy('name')->get()]);}
 public function storeJob(Request $r){$d=$r->validate(['customer_id'=>'required|exists:customers,id','technician_id'=>'nullable|exists:users,id','service_type'=>'required','scheduled_at'=>'required|date','duration_minutes'=>'required|integer|min:30','priority'=>'required','notes'=>'nullable','labor_cost'=>'required|numeric|min:0']); if($d['technician_id'] && ServiceJob::where('technician_id',$d['technician_id'])->where('scheduled_at',$d['scheduled_at'])->exists()) return back()->withErrors(['scheduled_at'=>'This technician already has a job at that time.'])->withInput(); $d['job_number']='TM3-'.now()->format('ymd').'-'.str_pad((string)(ServiceJob::count()+1),3,'0',STR_PAD_LEFT); ServiceJob::create($d); return back()->with('success','Service job booked and ready for dispatch.');}
 public function updateJobStatus(Request $r, ServiceJob $job){$d=$r->validate(['status'=>'required|in:Pending,Dispatched,In Progress,Completed,Cancelled']);$job->update($d); if($d['status']==='Completed') $this->createBilling($job); return back()->with('success','Job status updated.');}
 public function inventory(){return view('inventory.index',['items'=>InventoryItem::orderBy('name')->paginate(12)]);}
 public function storeInventory(Request $r){InventoryItem::create($r->validate(['sku'=>'required|unique:inventory_items,sku','name'=>'required','category'=>'nullable','stock'=>'required|integer|min:0','reorder_level'=>'required|integer|min:0','unit_price'=>'required|numeric|min:0']));return back()->with('success','Inventory item added.');}
 public function invoices(){return view('invoices.index',['invoices'=>Invoice::with('job.customer')->latest()->paginate(12)]);}
 public function pay(Request $r, Invoice $invoice){$d=$r->validate(['amount'=>'required|numeric|min:0.01','method'=>'required','reference'=>'nullable']); DB::transaction(function() use($d,$invoice){$invoice->payments()->create([...$d,'paid_at'=>now()]);$paid=$invoice->payments()->sum('amount');$invoice->update(['paid_amount'=>$paid,'status'=>$paid >= $invoice->total ? 'Paid' : 'Partial']);});return back()->with('success','Payment recorded.');}
 public function reports(){return view('reports.index',['completed'=>ServiceJob::where('status','Completed')->count(),'totalRevenue'=>Invoice::where('status','Paid')->sum('total'),'outstanding'=>Invoice::whereIn('status',['Unpaid','Partial'])->sum(DB::raw('total-paid_amount')),'commissions'=>Commission::with('technician')->latest()->take(10)->get(),'byService'=>ServiceJob::selectRaw('service_type, count(*) as total')->groupBy('service_type')->orderByDesc('total')->get()]);}
 private function createBilling(ServiceJob $job):void { if($job->invoice) return; $parts=$job->parts()->sum(DB::raw('quantity * unit_price'));$sub=(float)$job->labor_cost+(float)$parts;$tax=$sub*.12; $invoice=Invoice::create(['invoice_number'=>'INV-'.now()->format('ymd').'-'.str_pad((string)(Invoice::count()+1),3,'0',STR_PAD_LEFT),'service_job_id'=>$job->id,'subtotal'=>$sub,'tax'=>$tax,'total'=>$sub+$tax]); if($job->technician_id) Commission::firstOrCreate(['service_job_id'=>$job->id],['technician_id'=>$job->technician_id,'rate'=>10,'amount'=>$sub*.10]); }
}
